### ISSUE TITLE
access denied after creation of first repository

### ISSUE THREAD

**Issue by grubec** [elleFlorio/svn-docker#15] opened 2019-08-30 14:14 UTC
I followed the instructions and I can see a running server and can access it via svn and web (i.e. http://serverip/svn). A valid user is set via htpasswd and the credentials work well.
I used a fresh docker volume, mounted to /home/svn.

As soon as I create a repository via "docker exec -it svn-server svnadmin create /home/svn/testrepo" I won't get the repository page anymore, but the network connection is reset. I can't access the repository via svn:// eigther. When I use "docker exec -it svn-server ls -al /home/svn/testrepo" I get a valid listing for the newly created repository structure. I can see it in the volume directly as well.
If I delete the testrepo, the empty overview page at http:/serverip/svn becomes available again.

I could verify this behaviour on 2 different servers and also on a brandnew ubuntu 18.04 installation with docker and a rightful user that is part of the docker group.

Did I miss any access rights settings or do I have to alter any web_dav.conf settings to enable apache to access the repository properly?
Can anyone else confirm this behaviour?

Thank you very much in advance.

**Comment by elleFlorio** [comment] 2019-08-30 16:48
Hi @grubec,

It seams related to the problem reported in issue #12. Have a look at it and let me know what do you think! 😉

**Comment by zabetak** [comment] 2019-10-15 08:46
I can confirm that this is the same with issue#12.

**Comment by elleFlorio** [comment] 2019-10-16 19:53
Thank you @zabetak,

then I can close this since it is the same issue as the other one.

**Closed by elleFlorio** 2019-10-16 19:53 UTC
